// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVMVieX9CqriV4_KIJ8QZGkTMUdvfnEG4',
    appId: '1:152850783556:web:03652ffec33ae8f0910b11',
    messagingSenderId: '152850783556',
    projectId: 'learnify-96e03',
    authDomain: 'learnify-96e03.firebaseapp.com',
    storageBucket: 'learnify-96e03.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhJprHNvAy-5ZZ5feYkk8-73j4Dz-cS-g',
    appId: '1:152850783556:android:a0d02283492288ee910b11',
    messagingSenderId: '152850783556',
    projectId: 'learnify-96e03',
    storageBucket: 'learnify-96e03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkncMG27MUhZFYVPb-7vjguP41YSV1d3M',
    appId: '1:152850783556:ios:17d41745ef771109910b11',
    messagingSenderId: '152850783556',
    projectId: 'learnify-96e03',
    storageBucket: 'learnify-96e03.firebasestorage.app',
    iosBundleId: 'com.example.attendsure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkncMG27MUhZFYVPb-7vjguP41YSV1d3M',
    appId: '1:152850783556:ios:17d41745ef771109910b11',
    messagingSenderId: '152850783556',
    projectId: 'learnify-96e03',
    storageBucket: 'learnify-96e03.firebasestorage.app',
    iosBundleId: 'com.example.attendsure',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVMVieX9CqriV4_KIJ8QZGkTMUdvfnEG4',
    appId: '1:152850783556:web:74288d0055c7a390910b11',
    messagingSenderId: '152850783556',
    projectId: 'learnify-96e03',
    authDomain: 'learnify-96e03.firebaseapp.com',
    storageBucket: 'learnify-96e03.firebasestorage.app',
  );
}
